### ISSUE TITLE
`MultiLCA` class returning identical results under iteration

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2-calc#105]
[Original report](https://brightway.groups.io/g/development/topic/new_multilca_class_and/108054918)

Dear all,
 
I recently enjoyed the new MultiLCA class but i encountered diffilculties to do some Monte-Carlo calculations with it.
For a single demand and method LCA, I'm used to the usual syntax (for n Monte-Carlo runs) :

     
```python
    lca= bc.LCA( demand , method , use_distributions=True)
    lca.lci()
    lca.lcia()
    results=[lca.score for _ in zip(lca,range(n)) ]
```     

but with MultiLCA :

```python
    mlca = bc.MultiLCA( demands=functional_units ,method_config=config ,data_objs=data_objs,
        selective_use = {
            "technosphere_matrix" : {"use_distributions" : True},
            "biosphere_matrix" : {"use_distributions" : True},
            "characterization_matrix" : {"use_distributions" : False}
            })
    mlca.lci()
    mlca.lcia()
    results=[mlca.scores for _ in zip(mlca,range(n)) ]
```

I obtain a list of n identical dictionaries.
 
Do I miss something obvious on how to properly use the MultiLCA class for MC calculations ?
My option for now is to use naive and homemade slow functions to do MC calculations on several demands and methods, but if you have any optimized solution, it would be awesome !

**Comment by cmutel** [comment]
Added tests in 6d5235f2c6a6e260654e242ff371c970dc5c1d4d and 401b10f53da673031f68f8e060f4c02915b416a6 but cannot reproduce this behaviour.

**Comment by tchevilliet** [comment]
The error occurs for any random activities of ecoinvent 3.10 cutoff. In a project with ecoinvent database already imported :

```python

 eidb = bd.Database("ecoinvent-3.10-cutoff")
l_act = [eidb.random() for _ in range(3)] #list of 3 random activities
l_meth = [bd.methods.random() for _ in range(4)] #list of 4 random methods

```
Arguments for MultiLCA :

```python
fu = {f"{a}" : {a.id : 1.0 } for a in l_act}
config = {"impact_categories": l_meth}
data_objs = bd.get_multilca_data_objs(functional_units=fu,
                                      method_config=config)
```
It computes without error :

```python
n_MC = 10 # number of runs
# LCI and LCIA
mlca = bc.MultiLCA(
    demands=functional_units,
    method_config=config,
    data_objs=data_objs
    ,selective_use = {
        "technosphere_matrix" : {"use_distributions" : True},
        "biosphere_matrix" : {"use_distributions" : True},
        "characterization_matrix" : {"use_distributions" : True}
        }
    )
mlca.lci()
mlca.lcia()

results = [mlca.scores for _ in zip(mlca,range(n_MC))]

```
But we get an AssertionError  when we test the results
```python
aggregated = defaultdict(list)
for line in results:
    for k, v in line.items():
        aggregated[k].append(v)
for key, lst in aggregated.items():
    assert np.unique(lst).shape == (10,)
```

**Comment by cmutel** [comment]
@tchevilliet can you please post the versions of `matrix_utils` and `bw_processing` you are using? I recently made a change to add the possibility to use 64-bit index values, and the tests now run on both 32- and 64-bit index values, but maybe there is something subtly wrong.

Can you please also test that Monte Carlo works in the normal `LCA` class?

You can solve this problem (or at least I was able to) by reprocessing the database (i.e. `bd.Database("ecoinvent-3.10-cutoff").process()`), so there is something about the datapackages which is broken. However, I don't see a difference in the metadata, so am not sure where to even look.

**Comment by tchevilliet** [comment]
I use :

- matrix_utils v 0.4.3
- bw_processing v0.9.6

Normal LCA class works fine for stochastic LCA with the same activities and methods.
I tried to reprocess the database, but unfortunately it doesn't change the results.

**Comment by cmutel** [comment]
OK, then the 64-bit stuff is a red herring...

**Comment by cmutel** [comment]
The error here was checking for `inventory` instead of `inventories`, combined with the test varying the characterization matrix under Monte Carlo which meant that all the scores changed even if the technosphere didn't.

**Comment by tchevilliet** [comment]
Thanks a  lot, it's working perfectly well ! :+1:
