### ISSUE TITLE
All Monte Carlo calculations should support running without access to bw2data

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#14]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/14) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Needed for remote calculations. For example, `ParallelMonteCarlo` should only be passing processed array file paths instead of project, etc.

**Comment by cmutel** [comment]
Fixed in 2.0 development branch.
