### ISSUE TITLE
ParameterVectorLCA should make it easy to include parameter values

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#19]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/19) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Currently this is impossible, because only matrix presamples are included when loading presamples. Seems like the most reasonable approach would be to override `__init__`, and append the necessary space onto `self.sample`. Note that the current implementation doesn't preserve `self.sample`; it could be that a wrapper class would be easier in this case.

**Comment by cmutel** [comment]
Parameter vectors can be included via presamples - this is the "blessed" approach.
