### ISSUE TITLE
ParameterVectorLCA doesn't add presample values to `sample`

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#20]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/20) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

There is not easy way to fix this for the time being, however. Need to maintain presample behaviour where the last value is chosen (instead of adding as in matrix construction).

**Comment by cmutel** [comment]
`ParameterVector` functionality is being folded into the base LCA class in 2.5, so presamples will come for free.
