### ISSUE TITLE
to_dataframe sorting

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-calc#31]
Hi

I was having some trouble with `to_dataframe` and I see now it is commented. In case this method will be used at any point, I think `stacked.sort()` should be replaced by something like `stacked = stacked[:,stacked[0,:].argsort()]` (or anything more elegant).. otherwise the ranking is not well sorted.

**Comment by cmutel** [comment]
Fixed in 3f360c913f8d257aeabe4a7a754a1939de506c1a
