### ISSUE TITLE
ValueError: negative row index found during lcia calculation

### ISSUE THREAD

**Issue by BenPortner** [brightway-lca/brightway2-calc#32]
I cannot calculate any lcia results with the latest version of brightway on my 64-bit Windows machine. I receive an error claiming that the row indices passed during matrix building contain negative values. Stepping through the code, I found that there are not really any negative numbers. The problem is caused by faulty integer interpretations. The array of row indices contains the number `4294967295` which is interpreted as `-1` when cast to `int32` (which scipy.sparse.coo_matrix seems to do). The number is introduced by function `index_with_arrays` in [bw2calc/indexing.py](https://github.com/brightway-lca/brightway2-calc/blob/114c272a0fde9301ff5e250e2773c01c28d7fd99/bw2calc/indexing.py). It contains the following lines:

```python
index_array = np.zeros(keys.max() + 1) - 1
index_array[keys] = values

mask = array_from <= keys.max()
array_to[:] = -1 # array_to contains only 4294967295's
array_to[mask] = index_array[array_from[mask]]
array_to[array_to == -1] = MAX_SIGNED_32BIT_INT # replacement fails
```

Because the last line, the replacement step, fails the array still contains many 4294967295's when returned. For some weird reason, 4294967295 is not interpreted as -1 during the replacement but later during matrix building. Thus the error.

Possible solution (no error on my machine but didn't test it thoroughly yet):
```python
index_array = np.zeros(keys.max() + 1) - 1
index_array[keys] = values
index_array[index_array == -1] = MAX_SIGNED_32BIT_INT

mask = array_from <= keys.max()
array_to[:] = MAX_SIGNED_32BIT_INT 
array_to[mask] = index_array[array_from[mask]]
```

**Comment by cmutel** [comment]
I don't think this is still an open issue. We don't use magic numbers for masking arrays anymore, just -1 for missing values, and when we do use `MAX_SIGNED_32BIT_INT` in `matrix_utils`, it is (correctly) 2 billion instead of 4.
