### ISSUE TITLE
Create bw2remote and package functionality for offline calculations

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#4]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/4) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

This will be quite some work:

1. We need to be able to package up the processed files for a given functional unit and method (and weighting, normalization). This should be a single archive file.

2. Translate functional unit, etc. to the correct filenames and indices.

3. Write bw2remote, which is a flask application that can accept the files and a JSON payload.

4. bw2remote should then stream Monte Carlo results back to a notebook widget that will produce a dynamic D3 histogram. See: https://github.com/mbostock/d3/wiki/Histogram-Layout, http://stackoverflow.com/questions/22052694/how-to-update-d3-js-bar-chart-with-new-data, http://blog.thedataincubator.com/2015/08/embedding-d3-in-an-ipython-notebook/

bw2remote should use rq and redis: https://redis-py.readthedocs.org/en/latest/, http://python-rq.org/docs/, and a Queue during multiprocessing.

**Comment by cmutel** [comment]
Independent calculations, either locally or in the cloud, are already supported by 2.5 work. Work on a server interface should be documented in a separate repo.
