### ISSUE TITLE
fail to import brightway

### ISSUE THREAD

**Issue by tiago-furlan** [brightway-lca/brightway2-calc#64]
Hi there.
Guys, I am getting the following error when trying to import brightway.
_"AttributeError: module 'bw2calc' has no attribute 'ComparativeMonteCarlo'"_

In the link below I found a discussion regarding this same issue, however, I could not find the solution for my problem
https://github.com/brightway-lca/brightway2-calc/issues/43

Could someone help me, please?

Cheers.

**Comment by cmutel** [comment]
@tiago-furlan Please let us know if this is still an issue - the `brightway2` and `brightway25` metpackages should solve these installation incompatibilities.
