### ISSUE TITLE
Fail to install activity browser (Windows x64)

### ISSUE THREAD

**Issue by nejvas** [brightway-lca/brightway2-calc#74]
Dear all,

Following the instructions here (https://documentation.brightway.dev/en/legacy/source/setup/setup.html) to install brightway 2 for Windows x64 and the instructions here (https://github.com/LCA-ActivityBrowser/activity-browser#installation) to install the activity browser I never get past the command "conda create -n ab -c conda-forge activity-browser" (see below, username substituted by "xxx"). After getting the error message it seems it never stops "solving the environment", even if I wait for a longer time...

A friend has the same problem on his computer. Any ideas how we can address the problem? We tried both, working in the Anaconda Prompt and the Miniconda Prompt.

Many thanks!

Nejvas

```bash
(base) C:\Users\xxx>conda activate bw
(bw) C:\Users\xxx>conda install pywin32
Collecting package metadata (current_repodata.json): done
Solving environment: done
'# All requested packages already installed.
(bw) C:\Users\xxx>conda create -n ab -c conda-forge activity-browser
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
```

**Comment by michaelweinold** [comment]
Hey, @nejvas - thank you for filing the issue. Please note that the Activity Browser (AB) is a project that is mantained separately from Brightway. Brightway only provides the computational core for AB. If you experience issues with AB, please file an issue in their repo: https://github.com/LCA-ActivityBrowser/activity-browser#installation

However, having looked at [the documentation that they provide](https://github.com/LCA-ActivityBrowser/activity-browser#the-thorough-way) (to which you linked), it seems that you don't need to install Brightway separately __before__ installing AB. Instead, follow [their installation instructions](https://github.com/LCA-ActivityBrowser/activity-browser#install-the-ab-with-ecoinvent-39):

> ## Install the AB with ecoinvent >=3.9
> After prepending the Conda-Forge channel the following line should be executed within the command prompt/terminal to install the AB and it's dependencies.
> ```
> conda create -n ab activity-browser
> ```
> This will install the Activity Browser with the latest version of the Brightway2 libraries (currently excluding Brightway2.5 libraries).
