### ISSUE TITLE
Install brightway error

### ISSUE THREAD

**Issue by TrondL30** [brightway-lca/brightway2-calc#75]
Could anyone help me? I would like to install brightway2. 

(base) C:\Users\xxxxxxx>conda create -n bw brightway2 jupyterlab
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - brightway2

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by mfastudillo** [comment]
brightway's libraries are in the cmutel channel : https://anaconda.org/cmutel/brightway2

in the instructions for installation you can see an example of how to install it using conda

https://docs.brightway.dev/en/latest/content/setup/setup.html

`conda create -n bw -c cmutel brightway2 jupyterlab` should work
