### ISSUE TITLE
Use the expected value to parametrize lognormal distributions

### ISSUE THREAD

**Issue by Loisel** [brightway-lca/brightway2-calc#76]
I find it confusing that Brightway identifies the geometric mean of the lognormal distribution (i.e., the median of the distribution) with the `amount` given for an exchange when importing Ecospold2. I'm aware that this is in line with the ecospold specs, but in my opinion, it makes much more sense to choose the mean of the underlying normal distribution, $\mu$, such that the expected value for the resulting distribution (mean) is equal to the amount specified for the exchange. This approach is also followed by SimaPro as far as I can tell.

As can be seen [here](https://stackoverflow.com/questions/72660400/variation-between-montecarlo-mean-score-and-static-lca-score), I'm not the only one to find it confusing that the mean value from a MonteCarlo run is always noticeable above the static result.

The topic is also discussed in notebooks by @cmutel [here](https://github.com/brightway-lca/brightway2/blob/master/notebooks/Systematic%20bias%20in%20Monte%20Carlo%20medians.ipynb), and [here](https://github.com/brightway-lca/brightway2/blob/master/notebooks/Switch%20lognormal%20median%20to%20average.ipynb).

As far as I can tell, the discrepancy accumulates over the supply chain and eventually leads to resulting distributions with the static result being well below the median of the distribution.

I created a notebook where I reparametrized the lognormals choosing $\mu$ such that the expected value matches the amount of the exchange (basically following the steps described [here](https://github.com/brightway-lca/brightway2/blob/master/notebooks/Switch%20lognormal%20median%20to%20average.ipynb)), and did some basic tests. I cannot easily share the notebook in this issue, but the results look promising:
![average_vs_median](https://github.com/brightway-lca/brightway2-calc/assets/6737625/77e28c1f-4e8b-47ab-a240-171f1ac22953)

Shown are the ratios of a static LCA result vs the mean of MonteCarlo runs for 100 random processes and a random method for the original database and a version where I replaced $\mu$.

**Comment by cmutel** [comment]
@Loisel What would be your proposal here? I am not sure changing the default is great, it will upset quite a lot of people. But we could interpret the median as the mean, especially if we make this an optional config parameter.

Honestly I am not sure that ecoinvent has an official position on this. We can just do something as long as we can justify it.

**Comment by Loisel** [comment]
I do not understand what you mean by "interpret the median as the mean". What about having a parameter when creating the importer object, i.e., `SingleOutputEcospold2Importer`, for example `reparametrize_lognormal=True` or maybe something more concrete?
I can prepare a PR if there are no objections.
